spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: LJQ2003.
    url: jdbc:mysql://localhost:3306/store?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8

